---
  - name: install software-properties-common
    apt: name=software-properties-common state=latest
  
  - name: add certbot repository
    shell: add-apt-repository ppa:certbot/certbot

  - name: install certbot
    apt: name=certbot state=latest

  - name: Reload nginx to activate letsencrypt site
    service: name=nginx state=restarted

  - name: Create letsencrypt certificate
    shell: certbot certonly --standlone -m {{letsencrypt_email}} --agree-tos -d {{app_domain}} -d *.{{app_domain}} --server https://acme-v02.api.letsencrypt.org/directory

  - name: Generate dhparams
    shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
    args:
      creates: /etc/nginx/dhparams.pem

  - name: restart nginx
    service: name=nginx state=restarted

  - name: Add letsencrypt cronjob for cert renewal
    cron:
      name: letsencrypt_renewal
      special_time: monthly
      job: certbot --renew certonly --standlone -m {{letsencrypt_email}} --agree-tos -d {{app_domain}} -d *.{{app_domain}} --server https://acme-v02.api.letsencrypt.org/directory --pre-hook "service nginx stop" --post-hook "service nginx start"
    when: install_letsencrypt == "y"
