version: '3.8'

services:
  postgres:
    image: postgres:14.2
    container_name: ship-postgres
    networks:
      - ship
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5433:5432"
  api:
    container_name: ship-api
    build:
      context: .
      dockerfile: app/Api.Sql/Dockerfile
    networks:
      - ship
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3001
    ports:
      - "3001:3001"
  redis:
    image: redis:6.2.6
    container_name: ship-redis
    networks:
      - ship
  scheduler:
    container_name: ship-scheduler
    build:
      context: .
      dockerfile: app/Scheduler/Dockerfile
    networks:
      - ship
    environment:
      - DOTNET_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
networks:
  ship:
    name: ship