name: 'Base example update'

on:
  push:
    branches: [ master ]
    paths:
      - 'services/api-koa/**'
      - 'services/web/**'
      - 'packages/create-ship-app/**'
      - 'deploy/digital-ocean/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: 'Base example update'
        run: |
          git config --global user.email "github-actions"
          git config --global user.name "github-actions@github.com"
          cd examples
          rm -rf base
          chmod +x /home/runner/work/ship/ship/packages/create-ship-app/src/scripts/full-stack.sh
          bash /home/runner/work/ship/ship/packages/create-ship-app/src/scripts/full-stack.sh base /home/runner/work/ship/ship/packages/create-ship-app/src api-koa docker-compose-koa.yml Koa.js MongoDB digital-ocean/common digital-ocean/koa
          git add -A
          git commit -m 'update base example'
          git push origin master
